### PR TITLE
redirect command to output

### PR DESCRIPTION
**Pull request by jmecosta**
is this something you can use? redirect tool output to output window and send termination signal  once its done so the window requesting input will not show up?

### CODE REVIEW

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my very late answer. I make a break on _OpenCppCoverage Plugin_ to work on _OpenCppCoverage_ and then on other projects. Now I am back on this project!

I am also not fully happy with the current solution that displays a message at the end of the coverage.
Before doing this, I tried to redirect the message to the output window as you did. Unfortunately, output window seems to not support standard input redirection.
As some users may use standard input in their program, we cannot redirect message to the output window.

**Comment by jmecosta** [comment]
OK, weird that some users have this use case, since the window  is quite
annoying. Maybe make it configurable?

**Comment by OpenCppCoverage** [comment]
Hello,

My main usage of *OpenCppCoverage plugin* is running unit tests with GTest. 
In this case, a console is nice because GTest uses the terminal colours to display the results.

Do you have an use case in which the console is really annoying? Even when running an application, it is useful to see if there is an error at the end.

I try to design OpenCppCoverage to be easy to use and avoid adding several ways of doing the same thing except if there is a noticeable benefit.

OpenCppCoverage

**Comment by jmecosta** [comment]
we are using also gtest and we use the visual studio  test adapter https://marketplace.visualstudio.com/items?itemName=ChristianSoltenborn.GoogleTestAdapter and there are no pop ups anywhere. maybe thats the difference. the visual studio experience when in comes for testing and coverage tools in typical tools do not show popups, they run in background so they dont take your attention from what your doing. anyway this is just a difference to other coverage tools and test frameworks we use. if you think this is the way, then please close. thanks

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for this feedback. Indeed, when you run a test from *Test Explorer*, you do not want to have any windows because you know whether your test failed or not.
Ideally, we would like to run the coverage from *Test Explorer* and do not display any windows.

Do you know if it is possible to hook this plugin? I had a very quick look and do not see anything obvious.

OpenCppCoverage

**Comment by jmecosta** [comment]
Yes that's is the general develor workflow, so it really feels unnatural to
get those pop-ups ;) and all the output actually goes into the output
window also

Now to your question, I saw at some point some discussion in the opencover
extension regarding this, but ensure if they have added the support.  so
far I haven't seen any real implementation of this :(

**Comment by jmecosta** [comment]
Also I'm more than happy to use the Explorer to run tests,  and then press
produce coverage to see coverage and in this case the pop up is not needed
and in principle as you said the failures are already in the test explorer

**Comment by OpenCppCoverage** [comment]
Hello,

I am working now on the command line version of OpenCppCoverage and as this developement is not trivial, I have just had it to the [roadmap](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Roadmap#run-code-coverage-from-test-explorer-window).

OpenCppCoverage

**Pull request closed without merging**
