### PR TITLE
use opencppcover from program files, add setting to choose executable

### PR DESCRIPTION
**Pull request by jmecosta**
hi,

i am unable to build the extension, only if copying binaries of opencppcover into some folders this i then possible. probably a better approach is to not include the tool in the extension? feel free not to consider this

### CODE REVIEW

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my very late answer. I made a break on OpenCppCoverage Plugin to work on OpenCppCoverage and then on other projects. Now I am back on this project!

_OpenCppCoverage plugin_ can require a specific version of _OpenCppCoverage_. 
For example, if I rename a flag in _OpenCppCoverage_, plugin will not work with the latest version.
To make life easier for the end user, the version of _OpenCppCoverage_ is embbeded.

For developer, it is a little more complicated but everything is explained in the https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/blob/master/README.md file and so it should be ok.

**Comment by jmecosta** [comment]
Sure but can be made configurable? So you embedded one version and provide
a way to modify? It's common to find this in other extension also

**Comment by OpenCppCoverage** [comment]
Hello,

*"It's common to find this in other extension also".*
You are right, but my feeling is that people doing like that because it is easier for integration.
In the case of OpenCppCoverage, I cannot see the benefit.
New version of OpenCppCoverage may be incompatible with the latest version of the plugin. 
New plugin version may also be incompatible with an old version of OpenCppCoverage. 
I would like to avoid people creating an issue because of this problem.

If someone really wants to use another version, he can do it easily by overriding files but he should expect some issues.

OpenCppCoverage

**Comment by jmecosta** [comment]
ok, no worries.

**Pull request closed without merging**
