### PR TITLE
UX improvement

### PR DESCRIPTION
**Pull request by AlexKhotian**
Added <Toggle projects selection> button, improved ui behavior for BasicSettings

### CODE REVIEW

**Comment by OpenCppCoverage** [comment]
Hello,

Thanks a lot for the pull request! 
I am working on OpenCppCoverage command line and so do not have much time to work on the plugin but I will try to test it as soon as possible.

OpenCppCoverage

**Comment by AlexKhotian** [comment]
@OpenCppCoverage 
Thanks!

**Comment by KnitCoder** [comment]
Hello,

Do you know when there is a new version contaning this pull request? I have to deal with big projects and it would help me a lot.

Thanks!

**Comment by OpenCppCoverage** [comment]
@KnitCoder: I will try to create a release this week.

**Comment by OpenCppCoverage** [comment]
@AlexKhotian: Thank you very much for your contribution and sorry for my late answer!

**Pull request merged**
